version: "2"
services:
  web:
    build: .
    depends_on:
      - "db"
    ports:
      - "8080"
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=dostavim
    volumes:
      - ../scripts:/docker-entrypoint-initdb.d